name: Refresh Instagram Token

on:
  schedule:
    - cron: "0 0 */50 * *" # Runs every 50 days
  workflow_dispatch: # Allows manual triggering

jobs:
  refresh-token:
    runs-on: ubuntu-latest

    steps:
      - name: Call refreshInstagram endpoint
        run: |
          curl -X GET \
          -H "Authorization: Bearer ${{ secrets.NODE_API_TOKEN }}" \
          https://skenestunts.com/refreshInstagram
        env:
          GITHUB_TOKEN: ${{ secrets.NODE_API_TOKEN }}
